### ISSUE TITLE
Alias records fail when FQDN is not used.

### ISSUE THREAD

**Issue by dboitnot** [sigdba/sig-shared-sceptre#51]
In the MultihostELB template, when we have:

```yaml
route53:
  record_type: alias

...

listeners:
  - port: 443 
    hostnames: 
      - degreeworks  # No FQDN
```

We get the following error on launch:

```
RRSet with DNS name degreeworks. is not permitted in zone dwtest.scf.edu.
```

If we change the hostname to an FQDN the records get created.
