### ISSUE TITLE
Health check path not being set for EcsWebService

### ISSUE THREAD

**Issue by dboitnot** [sigdba/sig-shared-sceptre#63]
```yaml
      rules:
        - path: /BannerExtensibility
          host: banner-test.*
          health_check:
            path: /BannerExtensibility/actuator/health
```

Produces:

```yaml
    TargetGroupFORSLASHBannerExtensibilitySLASH:
      Properties:
        HealthCheckIntervalSeconds: 60
        HealthCheckPath: /BannerExtensibility/
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 30
```

Instead of:

```yaml
        HealthCheckPath: /BannerExtensibility/actuator/health
```
