### ISSUE TITLE
EcsWebService: Environment variable "sets"

### ISSUE THREAD

**Issue by dboitnot** [sigdba/sig-shared-sceptre#70]
It would be useful if there was a way to define a "set" of environment variables (or secrets) in a config file and add them to a container's environment with one line. I think the easiest way to deal with this would be to change `env_vars` and `secrets` from `Dict[str,str]` to `Union[Dict[str,str],List[Dict[str,str]]]`. So in cases where we want to use a set, we could put something like the following in a config file:

```yaml
saml_env_vars:
  metadata_url: https://whatever.school.edu
  logout_url: https://later-dude.school.edu
```

Then on the stack configuration:

```yaml
env:
  - {{ saml_env_vars }}
  - some_other_var: some_value
    yet_another_var: another_value
```

**Comment by dboitnot** [comment]
While working on this I noticed we can get weird parsing issues with the YAML and I'm not sure what to do about it. For instance, with this in `config.yaml`:

```yaml
env_var_set_2:
  evs_3: value_3
  evs_4: value_4
```

This works as expected:
```yaml
      secrets:
        - {{ env_var_set_2 }}
        - evs_3: override3
          something: wild
        - test: west
```

But this:
```yaml
      secrets:
        - {{ env_var_set_2 }}
        - evs_3: override3
          something: wild
```

Arrives at the validator as:
```python
{'evs_3': 'something'}
```
