### ISSUE TITLE
Error creating network load balancer

### ISSUE THREAD

**Issue by dboitnot** [sigdba/sig-shared-sceptre#92]
```
"An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unresolved resource dependencies [DefaultSecurityGroup] in the Resources block of the template"
```

This is because an ingress rule was created with a reference to an SG that isn't included in the template because NLBs don't have SGs.

```yaml
    IngressTO1521FORxulaDASHprodDASHserverDASHdb1DASHInstanceSg:
      Properties:
        Description:
          Ref: AWS::StackName
        FromPort: 1521
        GroupId:
          Fn::ImportValue: xula-prod-server-db1-InstanceSg
        IpProtocol: tcp
        SourceSecurityGroupId:
          Ref: DefaultSecurityGroup
        ToPort: 1521
      Type: AWS::EC2::SecurityGroupIngress
```
